### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kainjow** [DerekZiemba/DVDVideoScreensaver#1]
I was thinking of porting this to the Mac :) but that would require a license. Could you add one?

**Comment by DerekZiemba** [comment]
Do you have any suggested ones?

**Comment by kainjow** [comment]
MIT seems popular these days.

**Comment by DerekZiemba** [comment]
MIT License has been added. 

Now to make the animation less janky.  I tried refactoring it to WPF since I heard it has DirectX acceleration but all it did was increase memory usage from 31MB to 200MB. Thinking about going dotnetcore and using an OpenGL library. That would make it a lot more compatible with Mac too.
